### ISSUE TITLE
How do you know if the file upload status is uploaded?

### ISSUE THREAD

**Issue by LYXmoonstars** [tus/tus-js-client#102]
I use tus-js-client at angular4.0, and I want to call the typescript method in the upload success. Or what parameters are used to determine whether the current file is uploaded successfully.

**Comment by LYXmoonstars** [comment]
var options = {
          endpoint:'api/files',
          retryDelays: [0, 1000, 3000, 5000],
          headers: {'Authorization': 'Bearer ' + token},
   onError: function(error) {
            console.log("Failed because: " + error)
        },
        onProgress: function(bytesUploaded, bytesTotal) {
            var percentage = (bytesUploaded / bytesTotal * 100).toFixed(2)
            console.log(bytesUploaded, bytesTotal, percentage + "%")
        },
        onSuccess: function() {
            console.log("Download %s from %s", upload.file.name, upload.url)
**# // this.save();**  
        }
  };
 const upload = new tus.Upload(file, options);
  this.upload = upload;
}
public startUpLoad() {
    this.upload.start();
}
public save(): void {
}
I want to call the this.save () method in onSuccess，It's wrong.

**Comment by Acconut** [comment]
Sorry, but I am not able to understand your question. Please rephrase it or explain your situation in more detail. However, since you mentioned that you want to call `this.save()` in the `onSuccess` callback, I assume that you have a problem with the context of functions. As this is a very important topic in JavaScript (and also TypeScript), I recommend you to read this answer: https://stackoverflow.com/a/20279485.

As a quick fix for you, you should be able to access `this.save` by binding your callback:

```js
  // [...]
  },
  onSuccess: function() {
    console.log("Download %s from %s", upload.file.name, upload.url)
    this.save();
  }.bind(this) // <--
};
// [...]
```

**Comment by LYXmoonstars** [comment]
Thank you very much. According to the method you said, my problem has been solved.
