### ISSUE TITLE
Authorization header set in options, but not included in Request

### ISSUE THREAD

**Issue by MehdiFal** [tus/tus-js-client#122]
Hello, 

Thank you for this awesome lib!

I'm currently encountering an issue using the lib which is that the `Authorization` headers are not sent on the request even though I set it on the options.

This is how I set them:

```
let options = {
    endpoint: TUS_ENDPOINT,
    headers: {
        Authorization: 'Token myToken'
    },
    retryDelays: [0, 1000, 3000, 5000],
    metadata: oMetadata,
    onError: function(error) {  },
    onProgress: function(bytesUploaded, bytesTotal) {  },
    onSuccess: function() {  }
};

let upload = new tus.Upload(file, options);

upload.start();
```

So I get a 401 http code error, and when inspecting the request headers, I see that the `Authorization` header hasn't been added to the request even though I put it in the options.

I also tried to force the options before the `upload.start();` with:
`upload.options.headers =  { Authorization: 'Token myToken' };`
Which didn't work.

Any idea? 

Thank you.

**Comment by Acconut** [comment]
That's an interesting problem. I assume that you are running tus-js-client inside the browser and not inside Node.js, please correct me if I am wrong.

Would you be able to generate a HAR file and share it with us (see https://www.inflectra.com/support/knowledgebase/kb254.aspx)? HAR files contain the network traffic from a website, so we can inspect the sent and received headers more easily. If you don't want to share this file in the public you can also email me at marius@transloadit.com.

Besides that, I have already an idea: Before tus-js-client can send a POST request to create an upload, the browser will send an OPTIONS requests to check if the server allows the POST request. This OPTIONS request will not have set the Authorization header, since this is simply not possible. I assume that your server rejects this OPTIONS request since it does not have the Authorization header set. If that's the case, you might need to configure your server to allow OPTIONS requests without authorization. However, this is just an assumption, the HAR file will provide more details.

**Comment by calmdev** [comment]
I am using `authorization` header with this client. Make sure the preflight `OPTIONS` request responds with `authorization` in the list of allowed headers listed in the `access-control-allow-headers` header. Also, if you're using `node-tus-server`, make sure you're using the lastest release, because it includes [a merged PR](https://github.com/tus/tus-node-server/pull/103) which allows the `authorization` header to work properly.

<img width="895" alt="screen shot 2018-08-11 at 6 42 51 pm" src="https://user-images.githubusercontent.com/461249/43996784-76859b84-9d98-11e8-8b9c-0f0f0791ee42.png">

**Comment by MehdiFal** [comment]
@Acconut Thank you! You were right, that was related to the OPTIONS request indeed. 
I'm running tus-js-client in the browser indeed, so the workaround I did was to disable the security only for this `OPTIONS` endpoint, and basically just returned an empty 200 response.
(perfectly working now)

@calmdev Thank you! I'm however not using a Node JS server, currently pure Java.

Closing as resolved! :)

**Comment by djsg** [comment]
@MehdiFal do you have sample code on how to only disable security?
I added 
    headers: {
        Authorization: 'Token myToken'
    },
in my tus client code, I got error: request header filed authorization is not allowed by ...

**Comment by Acconut** [comment]
@djsg You likely have to add `Authorization` to the `Access-Control-Allow-Headers` header returned from your tus server in the responses. The exact code depends on your server/proxy setup.

**Comment by MehdiFal** [comment]
@djsg I ended up creating an empty, non-secure backend service `OPTIONS` which basically serves nothing but a `200` success response. 

It's not ideal given all my services were secure, but that's what i ended up doing with the time constraint I had.
