### ISSUE TITLE
PATCH returning HTTP Status=500 counts as success?

### ISSUE THREAD

**Issue by dviry** [tus/tus-js-client#124]
Hi,

I am using [uppy with the Tus uploader](https://github.com/transloadit/uppy/blob/eb0c681455866c06e2927f9486a1dd91f5ecd771/packages/%40uppy/tus/src/index.js#L182), and even though my tusdotnet server [returns an HTTP 500 error during the PATCH method](https://github.com/tusdotnet/tusdotnet/wiki/Processing-a-file-once-the-file-upload-is-complete), the tus-js-client still considers the upload a "success" and as such uppy considers it done.

I am pretty new to Tus/uppy, can you think of anything I am missing here?

Thanks in advance

**Comment by dviry** [comment]
After further investigations it seems that after the PATCH request (which fails) a HEAD request is also sent (which succeeeds), I am guessing tus-js-client then considers it "sort of OK" (I still personally think it should fail on the PATCH).
For now I've solved it by immediately deleting the file from the tusdotnet store, which causes the HEAD request also to fail (obviously not the best since the upload needs to happen again...)

**Comment by Acconut** [comment]
Hi there, apologies for the delayed response. I am not sure what causes the 500 error response from the tusdotnet server but that on its own does not look good to me.

Anyways, tus-js-client handles correctly in this case. It sees the error response and then sends a HEAD request to see how much of the file has already been uploaded. If the has not been fully uploaded, it will attempt to upload the remaining parts. After that is done, the upload is considered successful.

This error recovery is a major reason why tus exists. What other behavior would you have expected?

**Comment by dviry** [comment]
Thanks for your reply,

I think the issue I am having is that uploading the file (in my case - like in the Companion) is a 2 parts process:
- the upload itself
- the post-processing
There is no special "post-processing" handling in the "tusdotnet" server (I don't think it's actually part of the Tus protocoll?), the example says to do it after the upload - but if that fails (for whatever reason) this HTTP error 500 is returned (so post-processing failed), yet the client announces success. 
That is what surprised me - but I guess there must another way to enable the post-processing status to be "included" in the notification to the user (maybe like when using the Transloadit service)?

Thanks

**Comment by Acconut** [comment]
That's right, the upload and the post-processing are two separate processes where only the first one is defined by the tus protocol. Therefore, even if the post-processing fails, tus-js-client will consider it a success since the upload has completed. This is not necessarily designed like this but that's rather a result of how tus works.

In [tusd](https://github.com/tus/tusd), the post-processing step is invoked asynchronously meaning that it is started after the response for the PATCH request has been sent. Therefore a failed post-processing step cannot cause an error response. This seems to be differently handled in tusdotnet

> That is what surprised me - but I guess there must another way to enable the post-processing status to be "included" in the notification to the user (maybe like when using the Transloadit service)?

There is not built-in way for doing so. You would have to add a status endpoint to your API for checking if a post-processing step completed. Alternatively, you could try to avoid the post-processing steps from failing or add retries to them, depending on your application.

**Comment by dviry** [comment]
Thanks for your detailed answer, I guess I will have to sort it out myself...

This can now be closed.

**Comment by dviry** [comment]
Thanks for your detailed answer, I guess I will have to sort it out myself...

This can now be closed.
