### ISSUE TITLE
Suggestion to change default value of resume to false

### ISSUE THREAD

**Issue by codedokode** [tus/tus-js-client#127]
I think it would be better if the `resume` option would be `false` by default. The reasons are: 

- privacy. With this option enabled, a file hash is stored in browser storage without user knowing about it. 
- potential bugs. When the user closes a browser page, then opens a new page, they expect to start a new upload. But instead an old upload can be resumed which is unexpected. 

So I suggest to make it an opt-in for developers rather than default.

**Comment by kvz** [comment]
Hi there, thanks for your concerns. It is my belief that tus' purpose is increased reliability / salvaging more cat videos--and for this it is helpful to resume by default. The arguments against it that you mention, I feel can be solved in the user interface. (e.g. offer a "shall i resume question" and explain what is stored in local storage in your privacy / cookie policy)

**Comment by Acconut** [comment]
That's good point you bring up, @codedokode. In the past the behavior of the `resume` parameter has caused a lot of confusion and is in a lot of cases not really helpful when building real-world applications.

@kvz, I think that you are referring to the behavior of the `retryDelays` parameter. The sound related but how a very different meaning:
* `resume` controls whether we look into localStore to see if this file has been previously uploaded before. If so, we will continue this upload instead of starting a new upload.
The idea is nice for demos but is not always helpful in applications. For example, if you want to upload the same file twice (for example during testing or when you want to use a file in multiple different locations), the first upload will work as intended but the second upload is immediately complete without the server knowing that the file should be used somewhere else.
There have been numerous support requests where people have been confused by this behavior in the fast. Especially during testing it's something that's hard to track down. I remember that the people behind Uppy struggled for a long time to understand the parameter complete.
Furthermore, this parameter is not related to retries. So if the connection is interrupted while you upload, tus-js-client will not automatically restart the upload, you need to use `retryDelays` for that.
* `retryDelays` controls how often a failed request should be retried when the connection is interrupted or the server crashes for whatever reason. This is usually something everyone wants to have to improve reliability but unfortunately this parameter is disabled by default due to backwards compatibility.

I have thought in the past about renaming `resume` to something which capture its behavior better but I didn't find a good name. Another option is to give the user more control about if they want to resume a previous upload or start a new one by exposing a new API for retrieving/controlling the data from localStorage.

**Comment by codedokode** [comment]
I think by default `resume` (resume upload after page reload) should be off. So that only the developers who need this behaviour and understand how it works would enable this. 

This behaviour is unexpected and will cause different bugs. For example, imagine if the user starts a video upload, gets an upload URL, and while the file is uploading, fills the title, description, etc but doesn't tick the "Publish" checkbox. Then the user changes their mind, closes the page (before the video is completely uploaded), reopens it (and gets new upload URL and an empty form) and decides to upload the same file with other title. But the library will instead resume uploading that file at an old URL (which the server is not going to publish anyway). This will be confusing for both users and developers.

Or even worse, what if the user attaches the file to one form, then cancels the upload, goes to another form and attaches the same file again. Will it be uploaded to the first form anyway? 

Furthermore, I think the key in web storage should be not file's hash, but rather a combination of both has and upload endpoint URL. So that the upload is not resumed if you attach the file to another form.

Also, there should be an expiration timeout. If the user chooses the file they haven't uploaded a year ago, will it still try to resume the upload? That's ridiculous.

I think this option is not something that everyone needs and everyone is ready for. It should be off by default so that developers opt-in for this feature.

> I have thought in the past about renaming resume to something which capture its behavior better but I didn't find a good name.

I can suggest `resumeAfterReload`.

**Comment by kvz** [comment]
Ah sorry, I got confused about the name again indeed. So that's a +1 from me for changing it :) Breaking BC isn't fun, but I guess that's what major versions are for, and good names are a joy forever :) 

One could also consider not using `retry` for anything at all, then promoting `resumeAfterReload` (or however we're going to call it) in all documentation and examples, but under the hood aliasing `retry` to `resumeAfterReload` while logging a deprecation warning when this happens. That could make the adopting a change go a little bit smoother for folks.

**Comment by Acconut** [comment]
> @codedokode Also, there should be an expiration timeout. If the user chooses the file they haven't uploaded a year ago, will it still try to resume the upload? That's ridiculous.

It would try to resume the upload but the server likely has already removed the unfinished upload resource on its end. This would then trigger the client to simply start a new upload from scratch. So this exaggerated scenario is not really a pressing issue.

> @kvz One could also consider not using `retry` for anything at all

What do you mean with `retry`? tus-js-client does not have such an option. Did you mean `resume` or `retryDelays`?


Anyways, I thought a bit more about the current approach with `resume` and I came to the conclusion that it just lacks transparency, regardless of what name and default value we choose for it. The application has no way to ask tus-js-client what uploads have been started before and may be resumed. Furthermore, the application is only able to enable or disable this feature all together but it has no ability to know if an upload could be resumed in advance. Even worse, the application does not know at any stage if an upload is resumed from localStorage. I think that this is what causes the big confusion for the developers (and users): it is just hidden behind a too big abstraction layer.

Instead, I would like to propose removing the `resume` parameter entirely and instead adding an API to query tus-js-client for previously started uploads. The idea is that applications can use this information to see if they might want to resume a specific upload and even ask the end users for help if the application cannot make a decision. 

Here is a rough first example:

```js
// File object retrieved from an input element or something similar
const file = ...

// findPreviousUploads returns a list of uploads which previously uploaded the supplied file.
// The properties of the objects in the array might look like:
// => [{filename, filesize, filetype, uploadStartDate, lastUploadDate, endpoint, metadata, uploadUrl}]
const previousUploads = tus.findPreviousUploads(file)

// Filter out uploads which have been started for another form.
// In this example we only want to consider uploads for profile images.
const previousProfileUploads = previousUploads.filter((upload) => {
  return upload.metadata.formType === "profile-image"
})

// Ask the user if they want to continue one of the previous uploads
// or start a new upload instead. A return value of null indicates
// that a new upload should be started.
let uploadToResume = null
if(previousUploads.length > 1) {
  uploadToResume = askUserForComfirmationToResumeUpload(previousProfileUploads)
}

// Create a new tus.Upload instance which resumes or creates a new
// upload depending on the selected user input
let upload = null
if(uploadToResume !== null) {
  upload = new tus.Upload(file, { uploadUrl: uploadToResume.uploadUrl })
} else {
  upload = new tus.Upload(file)
}

// Start the upload as usual.
upload.start()
```

I know that this code is more verbose than the current example but it contains a lot more flexibility for the application. It would address the problems that @codedokode mentioned: uploads from a different form are resumed and uploads are resumed where the user does not want to resume them.

I might try to build an example app with this new API to see if it's any good in practice and if other tus clients should adopt a similar approach.

What do you think?

**Comment by Acconut** [comment]
My proposal is going to be implemented in the v2 release of tus-js-client. More details at https://github.com/tus/tus-js-client/issues/167.
