### ISSUE TITLE
v1.5.2 is breaking the request url

### ISSUE THREAD

**Issue by christieb7007** [tus/tus-js-client#137]
The request url is now using the current relative url instead of the `endpoint` passed to the `tus.Upload` object. This is happening for the subsequent PATCH calls and is not working as it is PATCHing to the wrong url

**Comment by Acconut** [comment]
From which tus-js-client version are you upgrading? Could it be 1.5.1? Also, can you provide us with an example to reproduce this?

**Comment by christieb7007** [comment]
Yes, I am upgrading from 1.5.1

Steps:
1. I created an upload object 
```
const upload = new tus.Upload(file, {
      resume: true,
      endpoint: "/some/relative/url/to/upload/to",
      ...
```
2. and proceed with `upload.start();`

3. This prompts a request to the correct URL, but the proceeding PATCH requests are not being directed to the endpoint url given. Instead they are PATCHing to the current application's url (which is not set up to do anything) 

The app being is also wrapped in a iFrame

**Comment by Acconut** [comment]
Ok, thanks for the clarification. That's an interesting setup, I have never seen someone using a relative endpoint URL. Would it be possible for you to use an absolute endpoint URL? I think this should be the quickest way for you to solve this problem.

In the 1.5.2 release we switched from a browser function for resolving URLs to a third-party module (the reason was to unify the behavior on the browser, nodejs and react native platforms). That's where this problem likely occurs.

>  Instead they are PATCHing to the current application's url (which is not set up to do anything)

What do you mean with application URL? Is it not sending the PATCH requests to something related to the upload URL?

**Comment by christieb7007** [comment]
Thanks for the response. The relative endpoint I am using is supposed to just use the current website domain (which are more than one) to get the full endpoint URL.
In trying to find the issue at first, I did notice the URL resolver showing different behavior - I agree that is where the issue is.

For your question: where I have the upload going is,

`https://mywebsite1.com/my/relative/upload/url/endpoint`
`https://mywebsite2.com/my/relative/upload/url/endpoint`
...

where say, my application is at `https://mywebsite2.com/myApp`, the upload url is expected to hit `https://mywebsite2.com/my/relative/upload/url/endpoint`, but the subsequent PATCHes are hitting `https://mywebsite2.com/myApp/my/relative/upload/url/endpoint`.

**Comment by christieb7007** [comment]
Sorry for the delay - we will fix on our end to use the absolute url
