### ISSUE TITLE
Support for uploading folders? Is there any example about uploading a folder with files?

### ISSUE THREAD

**Issue by EvgenyKislyy** [tus/tus-js-client#144]
Support for uploading folders? Is there any example about uploading a folder with files?
Instead of uploading files one by one?

**Comment by Acconut** [comment]
We don't have any special support or example code for uploading directories. I am not even sure if that's possible in a browser context due to security restrictions.

The only solution I see is to select the files on their own and upload them individually. Or you could tell the user to pack the files into a ZIP archive and upload that.

**Comment by kvz** [comment]
I do believe Uppy support(ed) uploading directories, or did i get that wrong @arturi ?

**Comment by arturi** [comment]
Uppy http://github.com/transloadit/uppy supports folders, yes, but the structure will be lost, so in the end you get a list of files.

You can also use a module, such as [`drag-drop`](https://www.npmjs.com/package/drag-drop), to then pass to `new tus.Upload()` in a loop.

**Comment by EvgenyKislyy** [comment]
Thanks guys!

**Comment by Acconut** [comment]
Great! I am going to close this issue since the question has been answered. Feel free to reopen this issue or create a new one if you have more questions.
