### ISSUE TITLE
Using a Readable for upload, push chunks?

### ISSUE THREAD

**Issue by endymonium** [tus/tus-js-client#194]
Hello,

can something like this work (Browser):

```
const Stream = require('stream')
const readable = new Stream.Readable()

var upload = new tus.Upload(readable , {
  uploadLengthDeferred: true,
  chunkSize: 1024 * 1024,
  etc
})
upload.start()

for (chunk of chunks) {
  readable.push(chunk) // chunk is of type Buffer, when pushed tus uploads it
}
readable.push(null) // at this point tus finishes the upload
```

I'm a newbie when it comes to streams & tus, so my pseudo code might also be totally off :) Is there any way to archive something like this?

Thanks!

**Comment by endymonium** [comment]
Ok, I managed to do something similar following https://github.com/tus/tus-js-client/blob/master/demos/browser/video.js, but I'm still wondering if this would work with native streams?

**Comment by Acconut** [comment]
Yes, tus-js-client supports reading from streams as shown in the demo you linked. However, since your code is compiled for a browser, tus-js-client only supports browser-style streams: https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Using_readable_streams. If you pass in a node-style stream, tus-js-client will return an error. I am not sure what you mean when talking about "native streams" but you should be able to write a wrapper around node-style streams to expose a browser-style stream API. Does that make sense?

**Comment by endymonium** [comment]
Ah I was creating node streams ... I always  fall into that trap :) By native I meant a native object, instead of the `readableRecorder` object from the above example. Now I'm using 

 ```
new ReadableStream({
  start (controller) {
  }
)
```

but get the error `source object may only be an instance of File, Blob, or Reader in this environment`. If the error comes from https://github.com/tus/tus-js-client/blob/84a87e91b54f6ddcd0cd20befac0bb23df183322/lib/browser/fileReader.js#L150 then it looks to me as if it is not actually checking for a `ReadableStream` but for the object described in https://github.com/tus/tus-js-client/pull/126 .

In that pull request it says that this implementation also does not support resuming (which I really need). Also I see no way to handle back pressure. 

Am I looking in the right code?

(Btw I'm in an electron environment)

**Comment by Acconut** [comment]
>  it looks to me as if it is not actually checking for a ReadableStream but for the object described in #126 .

That's correct. We don't check for a specific class (e.g. ReadableStream) but instead of the required interface is implemented (i.e. we need a `read` function that returns a Promise). 

> In that pull request it says that this implementation also does not support resuming

I think that changed by now. The PR is a year old and since then a few thing have been updated.

> Also I see no way to handle back pressure.

What kind of back pressure handling would you expect? I don't fully get what you mean.

**Comment by endymonium** [comment]
Regarding back pressure: to stop the chunk reader while an upload is happening. Reading your comments and the pull request again, I figured it out, I missed that `ReadableStream.getReader()` gives you a compatible object.

This example also helped me a lot: https://streams.spec.whatwg.org/#example-rs-push-backpressure

Thanks for your time :)

**Comment by Acconut** [comment]
Glad that you got it working!
