### ISSUE TITLE
Uploading over Nginx with Self Signed Certificate

### ISSUE THREAD

**Issue by dragoscirjan** [tus/tus-js-client#201]
**Question**
Hi! Is there a way I could upload files using `tus-js-client` over a Self Signed Certificate?
I completely dislike the idea of using `NODE_TLS_REJECT_UNAUTHORIZED=0` in order to bypass the certificates.

**Setup details**
- Runtime environment: Node.js
- Used tus-js-client version:  tus-js-client@1.8.0
- Used tus server software: tusd, under nginx

**Comment by Acconut** [comment]
tus-js-client has no special option for accepting self signed certificates since that should be handled by Node.js. Maybe you can add the certificate to the trusted list using this environment variable: https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file I have never tried it but that's the only idea I have.

**Comment by dragoscirjan** [comment]
Maybe an approach like this ( #203 ) would benefit everyone?

**Comment by Acconut** [comment]
Thanks for the PR but I am not sure if this is the best approach (see my comment over there).
