### ISSUE TITLE
onSuccess arguments

### ISSUE THREAD

**Issue by 1100100** [tus/tus-js-client#218]
I want to return customized data when the file upload is complete, and receive this data in the onSuccess callback. What should I do?

**Comment by Acconut** [comment]
Your exact idea is not possible. The onSuccess callback never receives an argument. However, you can use the onAfterResponse callback (https://github.com/tus/tus-js-client/blob/master/docs/api.md#onafterresponse) to inspect the responses and extract the data from there.

**Comment by mkgn** [comment]
Opening this because I get an error when using onAfterResponse() what I wanted to do was return some data back to client once the file is uploaded to server. So I added below method;

                onAfterResponse: function (req, res) {
                debugger;
                var url = req.getURL();
                var uploadedFile = res.getHeader("ca-uploaded-file");
                var error = res.getHeader("ca-error");

                if (uploadedFile) {//all ok?
                    console.log(uploadedFile);
                }

                if (error) {//all ok?
                    console.log(error);
                }
                console.log(`Request for ${url} responded with ${value}`);
            }
Once this method is added and tried to upload I see that file chunks are created at the server but then come to OnError with following error message.

tus: failed to create upload, caused by ReferenceError: value is not defined, originated from request (method: POST, url: /files, response code: n/a, response text: n/a, request id: n/a

If I comment this event code all works fine.

Any idea why?

**Comment by Acconut** [comment]
> Any idea why?

Yes, this is a bug in your code and not tus-js-client :)

You are trying to log the variable `value` but it is not defined:

> console.log(`Request for ${url} responded with ${value}`);

Remove this statement or use the appropriate variable and it should work.
