### ISSUE TITLE
`OPTION` is being triggered multiple times instead of first-time only.

### ISSUE THREAD

**Issue by iamriajul** [tus/tus-js-client#261]
**Describe the bug**
I think sending multiple `OPTION` requests are unnecessary for chunked uploading, making multiple `OPTION` request increases download latency.

![image](https://user-images.githubusercontent.com/24244379/119940251-bd89b500-bfb0-11eb-8fbd-2f6421b47f29.png)

**To Reproduce**
I'm using Vimeo's upload method, means passing uploadUrl instead of endpoint, and also passing low chunkSize: 1500000 bytes / 1.5MB

**Expected behavior**
I don't know much behind it, But I think the Tus client should only send `OPTION` request for the first-time.
If I'm wrong please pardon me.

**Screenshots**
![image](https://user-images.githubusercontent.com/24244379/119940747-7223d680-bfb1-11eb-88aa-9560668686b6.png)
See above screenshot.

As you can see all `OPTION` requests responses are same (except date). So wondering why multiple request is being sent for getting same response!

See below screenshot.
![image](https://user-images.githubusercontent.com/24244379/119940850-9b446700-bfb1-11eb-9fcd-374dc2692ca2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version tus-js-client: ^2.3.0

**Additional context**

Thanks.

**Comment by Acconut** [comment]
These OPTIONS requests are not sent by tus-js-client directly but automatically by your browser, as part of the CORS system. If you don't know what it is, I recommend to read up on it at https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS, otherwise my answer won't make much sense :)

We cannot control these OPTIONS request but normally these should be cached by the browser, so it is not necessary to resend them. This is also what I observe in Chrome. However, for some reason, Firefox does not cache these requests, so they are sent for every request. Frankly, I have no idea what the reason behind this is and whether it is a bug or not. Maybe you could report this behavior directly to Mozilla?

Also, have you considered increasing the chunk size? 1.5MB is very, very low.

**Comment by iamriajul** [comment]
Okay, got it. I'm aware of CORS system.

This maybe a bug of Mozilla, I also think this should be reported to Mozilla.

We have select form which lets the user selecting chunk size before starting upload. (user selects based upon their internet connection).
As Vimeo doesn't work well with tus.io resume capability, we had to do this. Do you know any better solution, that would be very helpful.
![image](https://user-images.githubusercontent.com/24244379/121124308-859f2f00-c846-11eb-8b63-48891153b722.png)
![image](https://user-images.githubusercontent.com/24244379/121124294-80da7b00-c846-11eb-83ca-92233eb58742.png)

Thanks.

**Comment by Acconut** [comment]
> I also think this should be reported to Mozilla.

Yes, would you be willing to take care of this?

> As Vimeo doesn't work well with tus.io resume capability, we had to do this.

Oh, ok, that's unfortunate. Maybe you can contact Vimeo and ask if there are any better alternatives. I do not have any advice in that case right now.

**Comment by iamriajul** [comment]
> Yes, would you be willing to take care of this?

I'm going through a very busy time at office, I think won't be able take care of this. You can submit the bug report to Mozilla if you're willing to.

Thanks.
