### ISSUE TITLE
tus-js-client with ocelot gateway don't work

### ISSUE THREAD

**Issue by apchenjun** [tus/tus-js-client#269]
Runtime environment:  chrome/edge Browser
Used tus-js-client version: npm 2.30
Used tus server software: .net core 3.1 and ocelot gateway 16.0.1
**tusdotnet and tus-js-client with ocelot gateway cannot resume transfer，When I pause, the progress starts from zero every time**。
tus-js-client with ocelot gateway an't generate .chunkstart extension name file ，When I pause and continue, I can’t start from the last upload position
![image](https://user-images.githubusercontent.com/4964551/124854520-071ae600-dfda-11eb-8124-8ca4a8ffe035.png)
Normal should produce .chunkstart extension name file 
![image](https://user-images.githubusercontent.com/4964551/124854582-1dc13d00-dfda-11eb-91ef-94086213d053.png)
log throw error message
![image](https://user-images.githubusercontent.com/4964551/124883259-ba4c0500-e003-11eb-8cc7-c6de327b277b.png)
ocelot config
![image](https://user-images.githubusercontent.com/4964551/124883292-c3d56d00-e003-11eb-99a5-5c2713050038.png)

**Comment by Acconut** [comment]
Please fill in all details as request when you open a new issue. Otherwise we cannot help you:


**Setup details**
Please provide following details, if applicable to your situation:
- Runtime environment: [e.g. Browser, Node.js, React Native]
- Used tus-js-client version: [can be obtained by running `npm ls`]
- Used tus server software: [e.g. tusd, tus-node-server etc]


Also, please explain what software you are using. I have never used any tus server, which generates a .chunkstart file.

**Comment by Acconut** [comment]
Closing this issue due to a lack of information. Feel free to leave a comment if you want to continue the discussion :)
