### ISSUE TITLE
Save to S3

### ISSUE THREAD

**Issue by CoreyH** [tus/tus-js-client#30]
Anyone have ideas for an easy way to save uploads directly to S3?

**Comment by Acconut** [comment]
Where uploads are actually stored (disk, database, S3 etc.) is the concern of the server and not the client. Therefore tus-js-client is not able to influence this decision.

However, the [tusd](https://github.com/tus/tusd) server (written in Go) supports S3 as an optional backend storage system: https://godoc.org/github.com/tus/tusd/s3store

Feel free to ask me about how to get this project running since it's a bit unintuitive at the moment :)
