### ISSUE TITLE
problems with upload from MSIE 11

### ISSUE THREAD

**Issue by markalanmiller** [tus/tus-js-client#33]
Hi,

I tried the demo, and it worked fine with FF.
But with MSIE, I tried twice and got the same failure message.
I chose an upload, then closed the tab, then revisited the page. and reselected the same file.
The upload seemed to complete, but then I got this message:
Failed because: Error: tus: No file to upload provided.

**Comment by kvz** [comment]
Thanks for reporting, we'll try to reproduce, what versions did you use?

**Comment by markalanmiller** [comment]
Hi, thanks for your response.
I used the demo on the tus web page, and MSEI 11.0.9600
And FF 45.0.2

Best,
Mark

**Comment by Acconut** [comment]
Sorry to hear you are having issues. Sadly, I will not be able to look into this one before next Monday. But I will check this definitely out coming week.

**Comment by markalanmiller** [comment]
Thanks ot is by no means urgent. Just letting you know I had an issue with your demo site.

Mark

On May 5, 2016, at 11:35 AM, Marius <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry to hear you are having issues. Sadly, I will not be able to look into this one before next Monday. But I will check this definitely out coming week.

**Comment by Acconut** [comment]
Thank you for reporting. I had a look into this and quickly found the issue's source which is not caused by tus-js-client directly but our demo scripts. The error occurs because we reset the file's input element after a successful upload which does not trigger an event in any other browser - except Internet Explorer. We then try to process the value of an input field which has just been reset and therefore crash. I will fix all occurrences of this and then report back!

**Comment by Acconut** [comment]
The version on http://tus.io/demo.html should be patched now.

**Comment by markalanmiller** [comment]
I tested and confirmed the fix. Thank you!
