### ISSUE TITLE
Tus uploads on Opera Mini

### ISSUE THREAD

**Issue by arturi** [tus/tus-js-client#34]
<img width="412" alt="screen shot 2016-05-05 at 19 38 21" src="https://cloud.githubusercontent.com/assets/1199054/15115857/f6ba5ba4-15ce-11e6-9389-f144a9d92f59.png">

Maybe we could take a look at why this might be failing and try to fix it? It’s a very popular mobile browser and the only way to use the internet for some people.

Can be tested with this: http://www.opera.com/developer/mobile-emulator

**Comment by Acconut** [comment]
Thank you for reporting this. I am able to reproduce this and will work an a fix.

**Comment by Acconut** [comment]
Here is what I found: This issue is not directly bound to Opera Mobile but is more a problem with the Presto engine which is still used by the Mobile Emulator. Newer versions of Opera Mobile now utilize Webkit/Blink as a render engine and should not have this issue.
Anyway, Opera 12 also uses Presto which is why you can reproduce this behavior in the desktop version, too. The root cause seems to be that you cannot set custom request headers for XMLHttpRequests if the destination has a different host than your current script. It could be related to some kind of same origin policy but I need to do some more investigation.

**Comment by Acconut** [comment]
The server has now been fixed, so even Presto works with it. Everything should be working now :)
