### ISSUE TITLE
Nuxt 3 on Cloudflare Workers

### ISSUE THREAD

**Issue by nicgene** [tus/tus-js-client#389]
**Question**
I'm trying to upload a file using the tus client on Cloudflare Workers but it keeps throwing an exception "URL.createObjectURL is not a function". Should I be using a ReadableStream instead?

My client:
```typescript
<script setup lang="ts">
const file = ref<HTMLInputElement>(null);

const onUpload = async () => {
  const upload = new tus.Upload(file.value.files[0], {
    endpoint: "/api/createUpload",
    ...
</script>

<template>
  <input ref="file" type="file" v-on:change="onUpload()">
</template>
```

**Setup details**
- Runtime environment: Browser, Workers
- Used tus-js-client version: 2.3.2
- Used tus server software: Cloudflare Stream

**Comment by Acconut** [comment]
Where is this exception thrown? In the browser or on the server side? What is the full stack trace of the exception? Please share more details in general.

**Comment by nicgene** [comment]
The exception is thrown on the server. Worker log below is very limited on details. I've created a minimal example that works correctly on localhost running `yarn dev` but when published to Workers is when it throws the exception.
https://github.com/nicgene/nuxt-cloudflare-tus-upoad
I wish I had more details for you.
```
{
  "outcome": "exception",
  "scriptName": null,
  "exceptions": [
    {
      "name": "TypeError",
      "message": "URL.createObjectURL is not a function",
      "timestamp": 1654618797594
    }
  ],
  "logs": [],
  "eventTimestamp": 1654618797594,
  "event": {
    "request": {
      "url": "https://[redacted].workers.dev/api/createUpload",
      "method": "POST",
      "headers": {
        "accept": "*/*",
        "accept-encoding": "gzip",
        "accept-language": "en-US,en;q=0.5",
        "cf-connecting-ip": "[redacted]",
        "cf-ipcountry": "US",
        "cf-ray": "717ab65cedd1fdd1",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "connection": "Keep-Alive",
        "content-length": "0",
        "dnt": "1",
        "host": "[redacted].workers.dev",
        "origin": "https://[redacted].workers.dev",
        "referer": "https://[redacted].workers.dev/",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-origin",
        "tus-resumable": "1.0.0",
        "upload-length": "11162178",
        "upload-metadata": "filename Y2l0eTIubXA0,filetype dmlkZW8vbXA0",
        "user-agent": "Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0",
        "x-forwarded-proto": "https",
        "x-real-ip": "[redacted]"
      },
      "cf": [redacted]
    }
  },
  "id": 2
}
```

**Comment by pipeu** [comment]
Thanks!

**Comment by Acconut** [comment]
@nicgene Would you mind sharing what solution solved your problem?

**Comment by nicgene** [comment]
I wasn't able to find a solution at the time. Tried setting "Content-Type": "application/offset+octet-stream" without any change.

The only other thing I can think of is if the HTTP stack isn't compatible? Nuxt 3 is using [Nitro](https://v3.nuxtjs.org/guide/concepts/server-engine)/[h3](https://github.com/unjs/h3) and claims to be compatible with Serverless, Workers, and Node.js.

I'm currently trying to solve this problem so if there is anything else I can try let me know. Thanks!

**Comment by Acconut** [comment]
Sorry to hear that it is not working for you so far. After another inspection, I believe your problem is not caused by your usage of tus-js-client. The exception is thrown on the server inside your request handler (https://github.com/nicgene/nuxt-cloudflare-tus-upoad/blob/c371d9258ee06b59f402bc499f92cb08cc955946/server/api/createUpload.post.ts) and not on the client-side (https://github.com/nicgene/nuxt-cloudflare-tus-upoad/blob/c371d9258ee06b59f402bc499f92cb08cc955946/pages/index.vue) where tus-js-client is actually used.

So as far as I understand, tus-js-client is not run inside the Cloudflare Workers but just inside the browser, where is should work fine. There is probably something wrong in your request handler, but I cannot help you with that.

**Comment by nicgene** [comment]
I believe you are correct. Yesterday I found an issue specific to the Nuxt 3 production build. Any request for a server API endpoint that accepts the POST method and doesn't contain a request body will throw the error "URL.createObjectURL is not a function".

Is there a way to specify a request body in the tus.Upload() as a workaround?

**Comment by Acconut** [comment]
Ok, so the problem is that the POST request from tus-js-client to your server endpoint has no body? Or that the request from your server to Vimeo has no body?

You cannot manually set the body for a request from tus-js-client as this is controlled by the logic for the upload process. If you want it to include part of the file to be uploaded in the initial POST request, have a look at the uploadDataDuringCreation option: https://github.com/tus/tus-js-client/blob/master/docs/api.md#uploaddataduringcreation. But I am not sure if that's what you are looking for.

However, the root cause in Nuxt should probably be fixed instead of working around this in such a way.
