### ISSUE TITLE
It seems it is possible to start/resume the same upload twice (or more)

### ISSUE THREAD

**Issue by fuad-tareq** [tus/tus-js-client#453]
It seems it is possible to start/resume the same upload for a file twice (or more). In such scenario, the PATCH requests double up and the progress bar starts zigzagging as a result, and the success callback ends up being triggered twice.

While the developer can definitely safeguard against this in the code, I believe it should be possible (and rather simple) for the tus-js-client to safeguard against this behavior so as to make it further foolproof.

Secondly, it seems the `tus.Upload` object does not have any information regarding whether the current upload is in progress, halted, or completed. I believe such information would be valuable to speed up development and would also be part of the solution to the above problem as well.

To solve both problems in the meantime, I had to use the data API to attach information regarding the current progress of the upload to the file DOM element. For example, when a `tus.Upload` is in progress, I'd do a `$('.file').data('tusUploadInProgress', 'true');`. And remove the variable when the `tus.Upload` fails or completes for that file. Of course this is just an example of what works in my case and this wouldn't work for everyone. It would have saved me quite some time to just be able to get this information from the `tus.Upload` object though (and would look prettier).

**Comment by Acconut** [comment]
> It seems it is possible to start/resume the same upload for a file twice (or more). In such scenario, the PATCH requests double up and the progress bar starts zigzagging as a result, and the success callback ends up being triggered twice.

Yes, this is correct. We have experienced this behavior before and the solution was to fix the user's code to avoid duplicate calls. We know this is not ideal. In the past, I have dabbled with the idea of use a state machine inside tus-js-client so that certain actions are not allowed for some state (e.g. call start if it has already been started). I did a first sketch of this flow in https://github.com/tus/tus-js-client/issues/355#issuecomment-1202324140. This would also provide information about the upload's state as you mentioned in your second point.

For now, this is not really a priority for us, but definitely a nice improvement for the future. What do you think?

**Comment by fuad-tareq** [comment]
Ah yes that should work nicely and would definitely solve both of my concerns.
