### ISSUE TITLE
demo site not working

### ISSUE THREAD

**Issue by yaseenayahya** [tus/tus-js-client#46]
tus.io demo site not uploading file... having error at 100% ..!!
 unexpected response while creating upload... 
using chrome... Version 53.0.2785.89 m

**Comment by Acconut** [comment]
Thank you for reporting! Since your description was not very informative, I deployed a new version to http://tus.io/demo.html which shows more details about the error causing the issue. Could you please try again and report back whether the same error appears? If so, also please include the full error message.

**Comment by yaseenayahya** [comment]
having this error now :
unexpected response while uploading chunk, originated from request(response code:500,response text:read tcp 10.99.128.27:8080->45.116.233.37:44015: i/o timeout)

**Comment by Acconut** [comment]
Perfect, that's actually a good sign. I/O timeouts occur when read and write operations are not completed in a predefined time window. We cannot do much in order to prevent these from happening but we can limit their impact drastically. I am currently working on the 1.4.0 release of tus-js-client which will include automated retries after errors. This basically means that, after we got it finish this week, the library will catch errors and continue the upload from where it was interrupted without the user or developer having to interfere. So please bear with us for the next few days.

**Comment by yaseenayahya** [comment]
Thanks for your support... I have one more thing to tell you...!!! I have 5 computers of same windows with same chrome version ...!!! On 2 its working perfect on other 2 not working..is something i have to do with internet explorer settings???

**Comment by Acconut** [comment]
Hi @yaseenayahya, I apologize for my late replay! Somehow your response slipped through my notifications.

> On 2 its working perfect on other 2 not working..is something i have to do with internet explorer settings???

There are plenty of reasons why a timeout may happen, ranging from different configurations and used software to how they are connected to the remote server. Even faulty wires may play a role. I am sorry but I cannot help you there.

Anyway, the 1.4.1 release of tus-js-client has been published and contains the automated retries feature I have mentioned the last time. This should eradicate the issues you were experiencing. Since this has also been deployed to tus.io/demo.html, I would be pleased if you could give it a try.
