### ISSUE TITLE
Where to contribute: lib or lib.es5?

### ISSUE THREAD

**Issue by mmathys** [tus/tus-js-client#51]
There are the directories `lib` and `lib.es5` in the root of the project.

Where is one supposed to make code changes? Is one folder generated from the other?

**Comment by Acconut** [comment]
As you can see from the scripts section in the `package.json` (https://github.com/tus/tus-js-client/blob/master/package.json#L69) the `lib.es5` directory is the transpiled version of the `lib` directory. Basically, changes should always go into `lib`. FYI, he `lib.es5` exists in order to allow users to require the module without utilizing an transpiler.
If you want to work on the demo, you can use the commands `npm run build` to build the `dist/tus.js` file or `npm run watch` to build it once and then watch for changes to the source file to trigger recompilations.

**Comment by mmathys** [comment]
Thanks!
