### ISSUE TITLE
concatenation extension support

### ISSUE THREAD

**Issue by gsmachado** [tus/tus-js-client#55]
Hello @Acconut,

First of all, I'm a big fan o tus.io. Nice work, congrats!
Secondly, this is not an issue -- it's more a comment/question.

What I want to know is: `tus-js-client` supports the concatenation extension?

I'm asking that because it would enhance the upload speed a lot if the client is able to upload several chunks in parallel.

If it's not implemented, what are the challenges or portions of code to be adapted/extended?

Cheers,
Guil.

**Comment by Acconut** [comment]
As the README says, the Concatentation extension is not supported: https://github.com/tus/tus-js-client#extension-support. The reason is that in the common browser environment one HTTP request is enough to fully utilize the uplink speed and using multiple requests would not increase the overall uploading stream. Of course, this may be different when you are using a local network or just have a good internet connection but, besides not needing this extension for now, there is no real reason why tus-js-client does not support it yet.

In order to implement it, I believe one would have to make several changes, I can't say out of my head. One especially tricky part would be how to handle Concatenation when you are uploading from a streaming source.

**Comment by tgouverneur** [comment]
I do think Concatenation implementation could dramatically improve certain use cases of Tus. I have several examples of people uploading with fiber connections over High Latency network who aren't able to maximize their upload speed using one stream. The benefits of parallel uploads and thus, of Concatenation extension would be tremendous in their case.

This would hence be awesome to have support for it ;-)

**Comment by Acconut** [comment]
@tgouverneur I see that there are use cases where the Concatenation extension would bring a lot of benefits. Pull requests are always appreciated, so if you are eager add this feature, I am happy to assist you with it :) My personal time for this project is limited, so I sadly cannot do it by myself.

**Comment by fidelix** [comment]
Please, can this be revisited?

The upload speeds for my target country is usually rubbish, and other solutions that are able to upload different parts at the same time are 6 to 10 times faster than tus-js-client in the browser (like Resumable.js).

**Comment by Acconut** [comment]
@fidelix Are you sure that uploading chunks in parallel will reduce your uploading duration? In most situations, tus-js-client is not the bottleneck but the tus server actually is. What does your setup look like?

**Comment by fidelix** [comment]
I am sure.

The issue here is with the client connection to the server being poor, not the server itself.

Creating multiple parallel uploads speed things up quite a bit (6-10 times depending on the number of connections).
We are talking about a difference between 150kbps of upload to 1/1.5mbps between tus-js-client and other alternatives that can upload chunks in parallel. The client connection I tested is from Brazil, and Japan, to an European tus (go) and tus-php server.

**Comment by Acconut** [comment]
I can understand your reasoning and I am am happy to assist you if you want to implement this feature. My personal time does not allow me to work on this on my own at the moment.

Besides that, parallel uploads using the concatenation extension should not be too hard to get working right now. The heavy lifting of doing the actual upload is already implemented inside tus-js-client. You only have to create multiple tus.Uploads with the correct `Upload-Concat: partial` headers set. After these uploads are all finished you manually issue a POST request with the `Upload-Concat: final; /files/a /files/b /files/c` to concatenate all of the chunks together. Maybe this helps you or anybody else how is interested in this.

**Comment by Acconut** [comment]
This feature will be implemented in tus-js-client v2: https://github.com/tus/tus-js-client/issues/167
