### ISSUE TITLE
supabase tus implementation

### ISSUE THREAD

**Issue by rares-lupascu** [tus/tus-js-client#620]
**Question**
We are using resumable tus uploads in supabase and found that in this part of the ex:
```
upload.findPreviousUploads().then(function (previousUploads) {
    // Found previous uploads so we select the first one.
    if (previousUploads.length) {
      upload.resumeFromPreviousUpload(previousUploads[0])
    }

    // Start the upload
    upload.start()
  })
```
the upload process does not get triggered and the way we fixed was by commenting
```
    if (previousUploads.length) {
      upload.resumeFromPreviousUpload(previousUploads[0])
    }
```

so is there anything wrong with our implementation? eventough tbh it is the almost copy and paste from the docs

- Runtime environment: NextJS on vercel
- Used tus-js-client version: 3.1.1 
- Used tus server software: Supabase (no idea)

**Comment by Mihai-github** [comment]
+1

**Comment by Mihai-github** [comment]
Hello @Acconut,

Thank you for your prompt response. Our concern doesn't revolve around removing any functionality. The issue we've encountered is related to the condition `previousUploads.length` being greater than zero. When this condition is met, we do not observe any ongoing uploads in the network tab of any content. Additionally, the files that have been added do not initiate the upload process. Essentially, this situation leaves the user unable to upload any files.

We are uncertain whether this issue is a result of something we might have done incorrectly, as we followed the example provided in the documentation. Therefore, we would greatly appreciate your or someone else assistance in resolving this matter, especially because the presence of this statement seems to be blocking any new uploads from functioning correctly.

Thanks!
