### ISSUE TITLE
Failed to upload chunk; file locked

### ISSUE THREAD

**Issue by arturi** [tus/tus-js-client#79]
Getting this sort of errors when using tus-js-client in Uppy from time to time:

<img width="875" alt="screen shot 2017-07-21 at 3 57 42 pm" src="https://user-images.githubusercontent.com/1199054/28667525-28072fba-72cc-11e7-9869-ca9f3d70e4bb.png">
<img width="1272" alt="screen shot 2017-07-21 at 12 23 16 pm" src="https://user-images.githubusercontent.com/1199054/28667526-2825c2fe-72cc-11e7-8117-c896437d9da4.png">

**Comment by Acconut** [comment]
This sometimes occurs when two PATCH requests are sent directly after each other and the first one is not properly ended. In this case, when the second request reaches the server, it thinks that the first is one still transferring and therefore considers the file locked.
However, usually this is not a problem since tus-js-client will automatically retry in such situations, if you enabled retries. Is this the case in Uppy?

**Comment by arturi** [comment]
Thanks for the help! I did add `retryDelays ` and it is way better now, haven’t been blocked by the issue since. I’ll re-open if this comes up again.
