### ISSUE TITLE
onProgress no fileID

### ISSUE THREAD

**Issue by devalexqt** [tus/tus-js-client#90]
Is it possible to get file id with  onProgress, onSuccess, onError event?

**Comment by devalexqt** [comment]
In my case, after uploading is completed, I extract media info on a server side and emit it back to client via socket.io and display it to html element, but I need to know that file id is associated with html element on the page.

**Comment by Acconut** [comment]
You can access the upload URL using [upload.url](https://github.com/tus/tus-js-client#tusuploadurl) in the onProgress (etc.) callbacks and extract the upload ID this way. tus-js-client does not provide a method for this extraction because the upload URL format depends on the server implementation and is not specified in the protocol. I hope this helps
