### ISSUE TITLE
Preserve cookies between requests

### ISSUE THREAD

**Issue by dcelasun** [tus/tus-js-client#92]
When the server responds with a `Set-Cookie` header to the initial `POST` request, the cookie(s) should be preserved in further (i.e `PATCH`, `GET`) requests.

This would allow load balancers with session affinity cookies to correctly route all requests of a single upload to the correct server.

**Comment by Acconut** [comment]
tus-js-client already has support for handling cookies in the described way. However, due to security reasons it has to be enabled before by setting the `withCredentials` option to true (see https://github.com/tus/tus-js-client#tusdefaultoptions and https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials for more details). I believe this should fix your problem, however, I am not able to test it out by myself right now.

**Comment by dcelasun** [comment]
Yep, that fixes it. Thanks!
