### ISSUE TITLE
Failed to patch file content

### ISSUE THREAD

**Issue by azharmalik3** [tus/tus-js-client#93]
I am using my own tusd server to upload the file. I am using the secure link for tusd server like `https://test.mysite.io/files`. 

When I checked xhr request on the console it shows post request send to `https` URL but patch and head request send to `HTTP (non-secure)` URL which caused to upload file contents.

Is there anything I need to add in the configuration?

**Comment by Acconut** [comment]
If you are running your server behind a proxy, you need to ensure that it has additional options enabled, depending on the software. If you are using tusd, you can find details in its FAQ section: https://github.com/tus/tusd#can-i-run-tusd-behind-a-reverse-proxy
Otherwise, please provide more information about your server.

**Comment by Acconut** [comment]
Closing this issue due to a lack of information. Feel free to leave a comment if you want to continue the discussion :)

**Comment by sneko** [comment]
Hi @Acconut ,

As @azharmalik3 mentioned, I specified a HTTPS endpoint to configure Tus, the POST will be made over this secure URL, but once Uppy tries to upload data (OPTIONS+HEAD methods), it fails due to uploading to non-secured HTTP.

Since I have some redirections to always make sure clients use the HTTPS endpoints... it makes the browser complaining.

Could you please indicate me why not all methods are done on HTTPS? Maybe that's not possible or not efficient to upload files chunks?

More details on my issue: https://github.com/transloadit/uppy/issues/2304

Thank you,
