### ISSUE TITLE
Saving content-type of the file

### ISSUE THREAD

**Issue by iballack** [tus/tus-js-client#95]
Hi guys,

Is it possible to save the Content-type of the original file on the client side?
Or it is done at the server side?

Im trying to modify the metadata of the uploaded object so that when the browser read my uploaded object (For example video file), it will not download instantly but it will treat it as a Video.

Any clues on this?

**Comment by Acconut** [comment]
As you correctly mentioned, the client should add the file's type as metadata to the upload and the server is then able to pick it up and proceed with that information as wanted. However, since serving uploaded content from your server with the original content type is a severe security vulnerability (an attacker can upload HTML and use it to steal the user's session from your side), most server implementations do not allow this. For example, tusd will force browser by default to download content.

Also, please be aware that tus server should not be used as file server since this is not the purpose they were built for (for example, they don't support caching or partial downloads). Instead, I would recommend to use proper software for this, such as Nginx or Apache.
